version: '3.4'

services:
  #reverseproxy:
    #build:
      #context: .
      #dockerfile: src/Nginx/Nginx.Dockerfile
    #restart: always
  seq:
    image: datalust/seq:latest

  sql.data:
    #image: mcr.microsoft.com/mssql/server:2019-latest
    image: microsoft/mssql-server-linux:2017-latest

  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile
    depends_on:
      - sql.data
      #- reverseproxy
    restart: always

  webbackgroundtasks:
    image: ${DOCKER_REGISTRY-}webbackgroundtasks
    build:
      context: .
      dockerfile: src/BackgroundServices/WebWorkerService/Dockerfile
    depends_on:
      - sql.data
      #- reverseproxy
    restart: always