// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMVC.Data;

namespace WebMVC.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200108150805_ShopViewModel")]
    partial class ShopViewModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.bankbookrecordseq", "'bankbookrecordseq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WebMVC.Applications.Queries.Bankbook.BankbookRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "bankbookrecordseq")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<decimal>("AmountChanged")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("BalanceId")
                        .HasColumnType("int");

                    b.Property<string>("DateOccurred")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("bankbookRecords");
                });

            modelBuilder.Entity("WebMVC.Applications.Queries.ShopAgents.ShopAgent", b =>
                {
                    b.Property<string>("ShopAgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateLastLoggedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasGrantRight")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wechat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShopAgentId");

                    b.ToTable("shopAgents","application");
                });

            modelBuilder.Entity("WebMVC.Applications.Queries.Shops.Shop", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateLastLoggedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateLastTrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wechat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShopId");

                    b.ToTable("shops","application");
                });

            modelBuilder.Entity("WebMVC.Applications.Queries.TraderAgents.TraderAgent", b =>
                {
                    b.Property<string>("TraderAgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateLastLoggedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasGrantRight")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wechat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TraderAgentId");

                    b.ToTable("traderAgents","application");
                });

            modelBuilder.Entity("WebMVC.Applications.Queries.Traders.Trader", b =>
                {
                    b.Property<string>("TraderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateLastLoggedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UplineUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wechat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TraderId");

                    b.ToTable("traders","application");
                });

            modelBuilder.Entity("WebMVC.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("BaseRoleType")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateLastLoggedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("QQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UplineId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Wechat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebMVC.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebMVC.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMVC.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebMVC.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMVC.Applications.Queries.ShopAgents.ShopAgent", b =>
                {
                    b.OwnsOne("WebMVC.Applications.Queries.Balances.ShopUserBalance", "Balance", b1 =>
                        {
                            b1.Property<string>("ShopAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<decimal>("AmountAvailable")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("AmountFrozen")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<int>("WithdrawalCommissionRateInThousandth")
                                .HasColumnType("int");

                            b1.HasKey("ShopAgentId");

                            b1.ToTable("shopAgents");

                            b1.WithOwner()
                                .HasForeignKey("ShopAgentId");

                            b1.OwnsOne("WebMVC.Applications.Queries.Balances.WithdrawalLimit", "WithdrawalLimit", b2 =>
                                {
                                    b2.Property<string>("ShopUserBalanceShopAgentId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<decimal>("DailyAmountLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.Property<int>("DailyFrequencyLimit")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("EachAmountLowerLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.Property<decimal>("EachAmountUpperLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.HasKey("ShopUserBalanceShopAgentId");

                                    b2.ToTable("shopAgents");

                                    b2.WithOwner()
                                        .HasForeignKey("ShopUserBalanceShopAgentId");
                                });
                        });

                    b.OwnsOne("WebMVC.Applications.Queries.Commission.RebateCommission", "RebateCommission", b1 =>
                        {
                            b1.Property<string>("ShopAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("RateRebateAlipayInThousandth")
                                .HasColumnType("int");

                            b1.Property<int>("RateRebateWechatInThousandth")
                                .HasColumnType("int");

                            b1.HasKey("ShopAgentId");

                            b1.ToTable("shopAgents");

                            b1.WithOwner()
                                .HasForeignKey("ShopAgentId");
                        });
                });

            modelBuilder.Entity("WebMVC.Applications.Queries.Shops.Shop", b =>
                {
                    b.OwnsOne("WebMVC.Applications.Queries.Balances.ShopUserBalance", "Balance", b1 =>
                        {
                            b1.Property<string>("ShopId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<decimal>("AmountAvailable")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("AmountFrozen")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<int>("WithdrawalCommissionRateInThousandth")
                                .HasColumnType("int");

                            b1.HasKey("ShopId");

                            b1.ToTable("shops");

                            b1.WithOwner()
                                .HasForeignKey("ShopId");

                            b1.OwnsOne("WebMVC.Applications.Queries.Balances.WithdrawalLimit", "WithdrawalLimit", b2 =>
                                {
                                    b2.Property<string>("ShopUserBalanceShopId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<decimal>("DailyAmountLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.Property<int>("DailyFrequencyLimit")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("EachAmountLowerLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.Property<decimal>("EachAmountUpperLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.HasKey("ShopUserBalanceShopId");

                                    b2.ToTable("shops");

                                    b2.WithOwner()
                                        .HasForeignKey("ShopUserBalanceShopId");
                                });
                        });

                    b.OwnsOne("WebMVC.Applications.Queries.Commission.RebateCommission", "RebateCommission", b1 =>
                        {
                            b1.Property<string>("ShopId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("RateRebateAlipayInThousandth")
                                .HasColumnType("int");

                            b1.Property<int>("RateRebateWechatInThousandth")
                                .HasColumnType("int");

                            b1.HasKey("ShopId");

                            b1.ToTable("shops");

                            b1.WithOwner()
                                .HasForeignKey("ShopId");
                        });
                });

            modelBuilder.Entity("WebMVC.Applications.Queries.TraderAgents.TraderAgent", b =>
                {
                    b.OwnsOne("WebMVC.Applications.Queries.Balances.Balance", "Balance", b1 =>
                        {
                            b1.Property<string>("TraderAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<decimal>("AmountAvailable")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("AmountFrozen")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<int>("DepositCommissionRateInThousandth")
                                .HasColumnType("int");

                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("WithdrawalCommissionRateInThousandth")
                                .HasColumnType("int");

                            b1.HasKey("TraderAgentId");

                            b1.ToTable("traderAgents");

                            b1.WithOwner()
                                .HasForeignKey("TraderAgentId");

                            b1.OwnsOne("WebMVC.Applications.Queries.Balances.WithdrawalLimit", "WithdrawalLimit", b2 =>
                                {
                                    b2.Property<string>("BalanceTraderAgentId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<decimal>("DailyAmountLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.Property<int>("DailyFrequencyLimit")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("EachAmountLowerLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.Property<decimal>("EachAmountUpperLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.HasKey("BalanceTraderAgentId");

                                    b2.ToTable("traderAgents");

                                    b2.WithOwner()
                                        .HasForeignKey("BalanceTraderAgentId");
                                });
                        });

                    b.OwnsOne("WebMVC.Applications.Queries.Commission.TradingCommission", "TradingCommission", b1 =>
                        {
                            b1.Property<string>("TraderAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("RateAlipayInThousandth")
                                .HasColumnType("int");

                            b1.Property<int>("RateWechatInThousandth")
                                .HasColumnType("int");

                            b1.HasKey("TraderAgentId");

                            b1.ToTable("traderAgents");

                            b1.WithOwner()
                                .HasForeignKey("TraderAgentId");
                        });
                });

            modelBuilder.Entity("WebMVC.Applications.Queries.Traders.Trader", b =>
                {
                    b.OwnsOne("WebMVC.Applications.Queries.Balances.Balance", "Balance", b1 =>
                        {
                            b1.Property<string>("TraderId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<decimal>("AmountAvailable")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("AmountFrozen")
                                .HasColumnType("decimal(18,3)");

                            b1.Property<int>("DepositCommissionRateInThousandth")
                                .HasColumnType("int");

                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("WithdrawalCommissionRateInThousandth")
                                .HasColumnType("int");

                            b1.HasKey("TraderId");

                            b1.ToTable("traders");

                            b1.WithOwner()
                                .HasForeignKey("TraderId");

                            b1.OwnsOne("WebMVC.Applications.Queries.Balances.WithdrawalLimit", "WithdrawalLimit", b2 =>
                                {
                                    b2.Property<string>("BalanceTraderId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<decimal>("DailyAmountLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.Property<int>("DailyFrequencyLimit")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("EachAmountLowerLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.Property<decimal>("EachAmountUpperLimit")
                                        .HasColumnType("decimal(18,0)");

                                    b2.HasKey("BalanceTraderId");

                                    b2.ToTable("traders");

                                    b2.WithOwner()
                                        .HasForeignKey("BalanceTraderId");
                                });
                        });

                    b.OwnsOne("WebMVC.Applications.Queries.Commission.TradingCommission", "TradingCommission", b1 =>
                        {
                            b1.Property<string>("TraderId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("RateAlipayInThousandth")
                                .HasColumnType("int");

                            b1.Property<int>("RateWechatInThousandth")
                                .HasColumnType("int");

                            b1.HasKey("TraderId");

                            b1.ToTable("traders");

                            b1.WithOwner()
                                .HasForeignKey("TraderId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
